name: Build Release
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
    inputs:
      prerelease_cli:
        description: 'Include pre-release CLI'
        required: false
        type: boolean
        default: false
      prerelease_patch:
        description: 'Include pre-release Patches'
        required: false
        type: boolean
        default: false
      prerelease_int:
        description: 'Include pre-release Integrations'
        required: false
        type: boolean
        default: false
      prerelease_xposed:
        description: 'Include pre-release Xposed'
        required: false
        type: boolean
        default: false
      prerelease_lspatch:
        description: 'Use nightly version of LSPatch'
        required: false
        type: boolean
        default: false
      prerelease_apk:
        description: 'Include pre-release APKs'
        required: false
        type: boolean
        default: false
      override_stable:
        description: 'Override release as stable'
        required: false
        type: boolean
        default: false
      manual_version:
        description: 'APK version code number (empty for auto)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          enable-cache: true
      - name: Install dependencies
        run: uv sync --frozen
      - name: Try building
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_THREAD_ID: ${{ secrets.TG_THREAD_ID }}
        run: |
          mkdir -p bins
          uv run main.py
